package config

type SQLDB struct {
	AccountsTable                 string
	ActivitiesTable               string
	AdsTable                      string
	AnalyticsTable                string
	AppealsTable                  string
	ArtistAlbumsTable             string
	ArtistEventsTable             string
	ArtistsTable                  string
	AuditlogsTable                string
	AutocompleteTable             string
	BaitoApplicationsTable        string
	BaitoTable                    string
	BaitoWorkerTable              string
	BlogPostsTable                string
	BookingsTable                 string
	BehindTheScenesTable          string
	CartTable                     string
	CatalogueTable                string
	ChatsTable                    string
	CommentsTable                 string
	CouponTable                   string
	CropsTable                    string
	CropsAboutTable               string
	DateCapsTable                 string
	DeliveriesTable               string
	DeliveryEventsTable           string
	DeliveryWebhooksTable         string
	DriversTable                  string
	DriverJobRejectionsTable      string
	EventsTable                   string
	FAQsTable                     string
	FarmsTable                    string
	FundingTable                  string
	FeedPostsTable                string
	FilesTable                    string
	FollowingsTable               string
	FarmOrdersTable               string
	HashtagTable                  string
	HiringTable                   string
	IdempotencyTable              string
	ItineraryTable                string
	JournalTable                  string
	LikesTable                    string
	MapsTable                     string
	MediaTable                    string
	MenuTable                     string
	MerchTable                    string
	MerechatTable                 string
	MessagesTable                 string
	ModeratorApplications         string
	NoticesTable                  string
	NotificationsTable            string
	NotificationsPreferencesTable string
	OrderTable                    string
	PlacesTable                   string
	ProductTable                  string
	PurchasedTicketsTable         string
	RecipeTable                   string
	RefundsTable                  string
	ReportsTable                  string
	ReviewsTable                  string
	RoleApplicationsTable         string
	ServiceTable                  string
	SettingsTable                 string
	SlotTable                     string
	SongsTable                    string
	StripeOrdersTable             string
	SubscribersTable              string
	TicketsTable                  string
	TiersTable                    string
	TransactionTable              string
	UserDataTable                 string
	UserTable                     string
	VendorTable                   string
	VendorAvailabilityTable       string
	AlbumsTable                   string
	PlaylistsTable                string
	GlobalLedgerTable             string
}

var Tables = SQLDB{
	AccountsTable:                 "accounts",
	ActivitiesTable:               "activities",
	AdsTable:                      "adverts",
	AlbumsTable:                   "albums",
	AnalyticsTable:                "analytics",
	AppealsTable:                  "appeals",
	ArtistEventsTable:             "artistevents",
	ArtistsTable:                  "artists",
	AutocompleteTable:             "autocomplete",
	AuditlogsTable:                "audit_logs",
	BaitoApplicationsTable:        "baitoapply",
	BaitoTable:                    "baitos",
	BaitoWorkerTable:              "baitoworkers",
	BlogPostsTable:                "blogposts",
	BookingsTable:                 "bookings",
	BehindTheScenesTable:          "bts",
	CartTable:                     "cart",
	CatalogueTable:                "catalogue",
	ChatsTable:                    "chats",
	CommentsTable:                 "comments",
	CouponTable:                   "coupons",
	CropsTable:                    "crops",
	CropsAboutTable:               "cropsabout",
	DateCapsTable:                 "date_caps",
	DeliveriesTable:               "deliveries",
	DeliveryEventsTable:           "deliveryEvents",
	DeliveryWebhooksTable:         "delwebhooks",
	DriverJobRejectionsTable:      "driver_rejection",
	DriversTable:                  "drivers",
	EventsTable:                   "events",
	FAQsTable:                     "faqs",
	FarmsTable:                    "farms",
	FeedPostsTable:                "feedposts",
	FilesTable:                    "files",
	FollowingsTable:               "followings",
	FarmOrdersTable:               "forders",
	FundingTable:                  "funding",
	GlobalLedgerTable:             "globalledger",
	HashtagTable:                  "hashtags",
	HiringTable:                   "hirings",
	IdempotencyTable:              "idempotency",
	ItineraryTable:                "itinerary",
	JournalTable:                  "journals",
	LikesTable:                    "likes",
	MapsTable:                     "maps",
	MediaTable:                    "media",
	MenuTable:                     "menu",
	MerchTable:                    "merch",
	MerechatTable:                 "merechats",
	MessagesTable:                 "messages",
	ModeratorApplications:         "modapps",
	NoticesTable:                  "notices",
	NotificationsTable:            "notifications",
	NotificationsPreferencesTable: "notificationpreferences",
	OrderTable:                    "orders",
	PlacesTable:                   "places",
	PlaylistsTable:                "playlists",
	ProductTable:                  "products",
	PurchasedTicketsTable:         "purticks",
	RecipeTable:                   "recipes",
	RefundsTable:                  "refunds",
	ReportsTable:                  "reports",
	ReviewsTable:                  "reviews",
	RoleApplicationsTable:         "role_applications",
	ServiceTable:                  "service",
	SettingsTable:                 "settings",
	SlotTable:                     "slots",
	SongsTable:                    "songs",
	StripeOrdersTable:             "stripeorders",
	SubscribersTable:              "subscribers",
	TicketsTable:                  "ticks",
	TiersTable:                    "tiers",
	TransactionTable:              "transactions",
	UserDataTable:                 "userdata",
	UserTable:                     "users",
	VendorTable:                   "vendors",
	VendorAvailabilityTable:       "vendor_availability",
}
